import {Injectable} from "@angular/core";
import {Match} from "../models/match";

Injectable()
export  class MatchService {


  ListMatch : Match [] = [

    {
      title1: 'Liverpool',
      title2: 'Arsenal',
      score1:'2',
      scorre2: '0',
      Likes :'1889',
      comments: '1153',
      stade: 'santiago bernabeu',
      championat:  'Première Ligue',
      brefDesc: 'Le talent du Sénégalais Sadio-Mané a fait toutes la difference dans ce Match',
      description : 'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l\'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux',
      date :  '19/Juin/2019',
      position :'1',
      possession: '60%',
      possession2 : '40%',
      Fautes: '4',
      Fautes2: '9',
      CoupFran: '4',
      CoupFran2: '6',
      passe: '489',
      passe2: '436',
      TirsC: '8',
      TirsC2: '6',
      corner: '6',
      corner2: '9',
      images: [
        'assets/imgs/logo/Li.png',
        'assets/imgs/equipe/s.jpg',
        'assets/imgs/joueurs/sd.jpg',
        'assets/imgs/equipe/liverpool.jpg',
        'assets/imgs/logo/LogoLigue.svg.png',
      ]
    },

    {
      title1: 'Manchester',
      title2: 'City',
      score1:'1',
      scorre2: '0',
      Likes :'1896',
      comments: '1188',
      stade: 'santiago bernabeu Stadium',
      championat:  'Première Ligue',
      brefDesc: "Ils l'ont fait, ils ont pu se qualifier et ont donnée une belle victoire aux supporteurs...",
      description : 'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l\'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux',
      date :  '22/Juin/2019',
      position: '3',
      possession: '59%',
      possession2 : '41%',
      Fautes: '9',
      Fautes2: '8',
      CoupFran: '8',
      CoupFran2: '3',
      passe: '369',
      passe2: '556',
      TirsC: '9',
      TirsC2: '6',
      corner: '4',
      corner2: '9',
      images: [
        'assets/imgs/logo/LogoManchester.png',
        'assets/imgs/equipe/Manch1.jpg',
        'assets/imgs/equipe/Manch2.jpg',
        'assets/imgs/equipe/Manch3.jpg',
        'assets/imgs/logo/LogoLigue.svg.png',
      ]
    },
    {
      title1: 'FC Barcelone',
      title2: 'Réal-Madrid',
      score1:'4',
      scorre2: '1',
      Likes :'1896',
      comments: '1188',
      stade: 'Wembley Stadium',
      championat:  'La ligua',
      brefDesc: 'Lionel Messi est désigné comme meilleurs Joueurs de ce match',
      description : 'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l\'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux',
      date :  '22/Juin/2019',
      position:'1',
      possession: '30%',
      possession2 : '60%',
      Fautes: '5',
      Fautes2: '12',
      CoupFran: '8',
      CoupFran2: '6',
      passe: '632',
      passe2: '456',
      TirsC: '9',
      TirsC2: '9',
      corner: '4',
      corner2: '4',
      images: [
        'assets/imgs/logo/logoBarca.png',
        'assets/imgs/joueurs/me.jpg',
        'assets/imgs/joueurs/me.jpg',
        'assets/imgs/joueurs/messi.jpg',
        'assets/imgs/logo/LogoLiga.png',
      ]
    },
    {
      title1: 'Paris',
      title2: 'Marseil',
      score1:'3',
      scorre2: '1',
      Likes :'1496',
      comments: '1288',
      stade: 'Paris Stadium',
      championat:  'Ligue 1',
      brefDesc: 'Grande Victtoir Pour Paris, Graçe à son Jeune Joueur Kylian Mbappé',
      description : 'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l\'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux',
      date :  '22/Juin/2019',
      position: '2',
      possession: '60%',
      possession2 : '40%',
      Fautes: '4',
      Fautes2: '9',
      CoupFran: '4',
      CoupFran2: '6',
      passe: '489',
      passe2: '436',
      TirsC: '8',
      TirsC2: '6',
      corner: '6',
      corner2: '9',
      images: [
        'assets/imgs/logo/paris.svg.png',
        'assets/imgs/equipe/paris.jpg',
        'assets/imgs/equipe/paris2.jpg',
        'assets/imgs/joueurs/ne.jpg',
        'assets/imgs/logo/LogoParis.svg.png',
      ]
    },
    {
      title1: 'Réal-Madrid',
      title2: 'Villa-Real',
      score1:'5',
      scorre2: '1',
      Likes :'1896',
      comments: '1188',
      stade: 'Wembley',
      championat:  'Première Ligue',
      brefDesc: "le real s'impose avec un lourd score à domicile, ce qui lui garentie une bonne suite pour le...",
      description : 'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l\'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux',
      date :  '22/Juin/2019',
      position: '3',
      possession: '59%',
      possession2 : '41%',
      Fautes: '4',
      Fautes2: '9',
      CoupFran: '4',
      CoupFran2: '6',
      passe: '499',
      passe2: '536',
      TirsC: '12',
      TirsC2: '5',
      corner: '6',
      corner2: '9',
      images: [
        'assets/imgs/logo/LogoReal.svg.png',
        'assets/imgs/equipe/Real1.jpg',
        'assets/imgs/equipe/Real2.jpg',
        'assets/imgs/equipe/Real3.jpg',
        'assets/imgs/logo/LogoLiga.png',
      ]
    },
    {
      title1: 'Bayern',
      title2: 'Arsenal',
      score1:'0',
      scorre2: '2',
      Likes :'1896',
      comments: '1188',
      stade: 'santiago bernabeu',
      championat:  'Première Ligue',
      brefDesc: 'Grosse déception de la part des supporteur du Bayern apres un echec à domicile face à ....',
      description : 'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l\'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux',
      date :  '22/Juin/2019',
      position: '1',
      possession: '60%',
      possession2 : '40%',
      Fautes: '4',
      Fautes2: '9',
      CoupFran: '4',
      CoupFran2: '6',
      passe: '489',
      passe2: '436',
      TirsC: '8',
      TirsC2: '6',
      corner: '6',
      corner2: '9',
      images: [
        'assets/imgs/logo/Arsenal_FC.svg',
        'assets/imgs/equipe/bayern1.jpg',
        'assets/imgs/equipe/bayern2.jpg',
        'assets/imgs/equipe/bayern3.jpg',
        'assets/imgs/logo/LogoLigue.svg.png',
      ]
    },
    {
      title1: 'Chealse',
      title2: 'Atletico',
      score1:'2',
      scorre2: '1',
      Likes :'1896',
      comments: '1188',
      stade: 'Wembley',
      championat:  'Première Ligue',
      brefDesc: 'La tactique du Coath au final à bien fonctionner , les joueurs ce sont rattrapé ',
      description : 'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l\'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux',
      date :  '22/Juin/2019',
      position: '4',
      possession: '60%',
      possession2 : '40%',
      Fautes: '4',
      Fautes2: '9',
      CoupFran: '4',
      CoupFran2: '6',
      passe: '489',
      passe2: '436',
      TirsC: '8',
      TirsC2: '6',
      corner: '6',
      corner2: '9',
      images: [
        'assets/imgs/logo/LogoChealse.png',
        'assets/imgs/equipe/chealse1.jpg',
        'assets/imgs/equipe/chealse2.jpg',
        'assets/imgs/equipe/chealse3.jpg',
        'assets/imgs/logo/LogoLigue.svg.png',
      ]
    },
    {
      title1: 'Marseille',
      title2: 'Lyon',
      score1:'3',
      scorre2: '1',
      Likes :'1896',
      comments: '1188',
      stade: 'santiago bernabeu Wembley',
      championat:  'Première Ligue',
      brefDesc: 'Lionel Messi est désigné comme meilleurs Joueurs de ce match',
      description : 'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l\'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux',
      date :  '22/Juin/2019', possession: '60%',
      position: '3',
      possession2 : '40%',
      Fautes: '4',
      Fautes2: '9',
      CoupFran: '4',
      CoupFran2: '6',
      passe: '489',
      passe2: '436',
      TirsC: '8',
      TirsC2: '6',
      corner: '6',
      corner2: '9',
      images: [
        'assets/imgs/logo/marseille.svg',
        'assets/imgs/equipe/Marseille3.jpg',
        'assets/imgs/equipe/Marseille2.jpg',
        'assets/imgs/equipe/Marseille1.jpg',
        'assets/imgs/logo/LogoLiga.png',
      ]
    }

  ]
}
